version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_api
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minha_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_api_network

volumes:
  postgres_data:

networks:
  minha_api_network:
